# image
FROM php:8.2-apache

# config
COPY ./apache2.conf /etc/apache2/
COPY ./php.ini /usr/local/etc/php/
RUN echo 'alias ll="ls -la"' >> ~/.bashrc
RUN echo ':set encoding=utf-8' >> ~/.vimrc
RUN echo 'syntax on' >> ~/.vimrc

# modrewrite
RUN mv /etc/apache2/mods-available/rewrite.load /etc/apache2/mods-enabled
RUN /bin/sh -c a2enmod rewrite

# Install
RUN apt-get update
RUN apt-get install -y vim
RUN apt-get install -y libonig-dev
RUN apt-get install -y zip
RUN apt-get install -y git
RUN apt-get install -y curl
RUN apt-get install wget

# composer
RUN curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer

# node
RUN apt-get install -y nodejs npm && npm install n -g

# yarn
RUN wget https://github.com/yarnpkg/yarn/releases/download/v1.22.19/yarn_1.22.19_all.deb
RUN dpkg -i yarn_1.22.19_all.deb

# pdo
RUN docker-php-ext-install pdo_mysql mysqli

# cron
RUN apt-get install -y cron
RUN /etc/init.d/cron start
